import: models.riemannian_restart:RiemannianRestartModel
init:
  sigma0: 0.5
  max_gen: 50000
  seed: 42
  restarts: 10
  energy:
    import: frameopt.core.energy:pnormmax_coherence
    kwargs:
      p: 20